import { watchAuth, loginUser, logoutUser, registerUser, resetPassword } from "./auth.js";
import { isConfigured } from "./firebase-init.js";
import { loadUserRecipes, saveRecipe, removeRecipe } from "./recipes.js";
import { updateProfile, getShoppingList, saveShoppingList, setRecipeFavorite } from "./database.js";
import { escapeHtml, formatDate, friendlyError, icon, setBusy, toast } from "./ui.js";

const state = {
  user: null, profile: null, recipes: [], query: "", category: "Todas", sort: "recent",
  editingId: null, currentRecipe: null, imageFile: null, imageUrl: "", imagePath: "",
  shoppingList: [], timer: null, timerSeconds: 0, timerTotal: 0
};
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const categories = ["Bolos","Doces","Salgados","Massas","Carnes","Acompanhamentos","Bebidas","Pães","Molhos","Outros"];

function initials(name = "?") { return name.trim().split(/\s+/).slice(0,2).map(p => p[0]).join("").toUpperCase() || "?"; }
function showScreen(screen) { $("#app-loader").classList.add("hidden"); $("#auth-screen").classList.toggle("hidden", screen !== "auth"); $("#main-app").classList.toggle("hidden", screen !== "app"); }
function navigate(view, params = {}) {
  if (!state.user && view !== "dashboard") return;
  $$(".view").forEach(el => el.classList.remove("active"));
  const target = $(`#view-${view}`); if (target) target.classList.add("active");
  $$(".nav-item[data-view]").forEach(el => el.classList.toggle("active", el.dataset.view === view));
  if (view === "dashboard") renderDashboard();
  if (view === "recipes") renderRecipes();
  if (view === "form") renderForm(params.id || null);
  if (view === "detail") renderDetail(params.id);
  if (view === "settings") renderSettings();
  window.scrollTo({ top: 0, behavior: "smooth" }); closeMobileMenu();
}

function recipeCard(recipe) {
  const title = escapeHtml(recipe.title || "Sem título");
  const category = escapeHtml(recipe.category || "Receita caseira");
  const image = recipe.imageUrl ? `<img src="${escapeHtml(recipe.imageUrl)}" alt="${title}" loading="lazy">` : `<div class="recipe-placeholder"><span>🍽️</span><small>Sem foto</small></div>`;
  return `<article class="recipe-card" data-recipe-id="${recipe.id}"><div class="recipe-image">${image}<button class="favorite-dot ${recipe.favorite ? "is-favorite" : ""}" data-favorite="${recipe.id}" aria-label="${recipe.favorite ? "Remover dos favoritos" : "Favoritar"}">${icon("heart")}</button></div><div class="recipe-card-body"><span class="tag">${category}</span><h3>${title}</h3><p>${escapeHtml(recipe.description || "Uma receita especial do seu caderno.")}</p><div class="card-meta"><span>${recipe.prepTime ? `${icon("clock")} ${escapeHtml(recipe.prepTime)}` : formatDate(recipe.updatedAt || recipe.createdAt) || "Receita salva"}</span><span>${icon("arrow")}</span></div></div></article>`;
}
function emptyState(title, text, buttonLabel, view) { return `<div class="empty-state"><div class="empty-plate">🍲</div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(text)}</p><button class="btn btn-primary" data-view="${view}">${icon("plus")} ${escapeHtml(buttonLabel)}</button></div>`; }

function renderDashboard() {
  const name = escapeHtml(state.profile?.displayName || state.user?.displayName || state.user?.email?.split("@")[0] || "Chef");
  const recent = state.recipes.slice(0, 4);
  const favs = state.recipes.filter(r => r.favorite).length;
  const unchecked = state.shoppingList.filter(i => !i.checked).length;
  $("#view-dashboard").innerHTML = `<div class="topbar"><div><span class="eyebrow">SEU CADERNO DIGITAL</span><h1>Olá, ${name}!<br><em>O que vamos preparar hoje?</em></h1></div><button class="avatar-button desktop-avatar" data-view="settings"><span>${initials(name)}</span></button></div>
  <div class="hero-card"><div class="hero-copy"><span class="hero-kicker">SABOR QUE FICA</span><h2>Suas receitas,<br><strong>do seu jeito.</strong></h2><p>Organize seus preparos favoritos em um só lugar e cozinhe sem perder nenhum detalhe.</p><button class="btn btn-light" data-view="form">${icon("plus")} Adicionar receita</button></div><div class="hero-ingredients" aria-hidden="true"><span class="orb orb-1">🍋</span><span class="orb orb-2">🌿</span><span class="orb orb-3">🌶️</span><span class="orb orb-4">🍅</span></div></div>
  <div class="stat-row"><div class="stat-card"><span class="stat-icon">${icon("book")}</span><div><strong>${state.recipes.length}</strong><small>receita${state.recipes.length===1?"":"s"} salva${state.recipes.length===1?"":"s"}</small></div></div><div class="stat-card accent"><span class="stat-icon">${icon("heart")}</span><div><strong>${favs}</strong><small>favorita${favs===1?"":"s"}</small></div></div><button class="stat-card shopping-stat" id="open-shopping"><span class="stat-icon">${icon("cart")}</span><div><strong>${unchecked}</strong><small>item${unchecked===1?"":"s"} na lista</small></div></button></div>
  <section class="section-block"><div class="section-heading"><div><span class="eyebrow">SEU ACERVO</span><h2>Receitas recentes</h2></div><button class="link-button" data-view="recipes">Ver todas ${icon("arrow")}</button></div>${recent.length ? `<div class="recipe-grid compact">${recent.map(recipeCard).join("")}</div>` : emptyState("Ainda não há receitas","Comece adicionando aquela receita que você nunca quer esquecer.","Adicionar receita","form")}</section>`;
}

function renderRecipes() {
  let filtered = state.recipes.filter(r => `${r.title||""} ${r.category||""}`.toLowerCase().includes(state.query.toLowerCase().trim()));
  if (state.category !== "Todas") filtered = filtered.filter(r => (r.category || "Outros") === state.category);
  if (state.sort === "favorites") filtered = filtered.filter(r => r.favorite);
  if (state.sort === "name") filtered.sort((a,b) => (a.title||"").localeCompare(b.title||"", "pt-BR"));
  else filtered.sort((a,b) => (b.updatedAt||b.createdAt||0)-(a.updatedAt||a.createdAt||0));
  $("#view-recipes").innerHTML = `<div class="page-heading"><div><span class="eyebrow">SEU ACERVO</span><h1>Minhas receitas</h1><p>Todos os sabores que você decidiu guardar.</p></div><button class="btn btn-primary" data-view="form">${icon("plus")} Nova receita</button></div>
  <div class="search-row"><div class="search-box">${icon("search")}<input id="recipe-search" type="search" value="${escapeHtml(state.query)}" placeholder="Buscar por nome ou categoria…" autocomplete="off"></div><select id="sort-select" class="filter-select"><option value="recent" ${state.sort==="recent"?"selected":""}>Mais recentes</option><option value="favorites" ${state.sort==="favorites"?"selected":""}>Favoritas</option><option value="name" ${state.sort==="name"?"selected":""}>Por nome</option></select></div>
  <div class="category-scroller"><button class="category-chip ${state.category==="Todas"?"active":""}" data-category="Todas">Todas</button>${categories.map(c=>`<button class="category-chip ${state.category===c?"active":""}" data-category="${c}">${c}</button>`).join("")}</div>
  ${filtered.length ? `<div class="recipe-grid">${filtered.map(recipeCard).join("")}</div>` : emptyState(state.sort==="favorites"?"Nenhuma favorita ainda":state.query||state.category!=="Todas"?"Nada encontrado":"Seu caderno está esperando",state.sort==="favorites"?"Toque no coração de uma receita para adicioná-la aqui.":"Tente outro nome, categoria ou salve sua primeira receita.",state.query||state.category!=="Todas"?"Limpar filtros":"Adicionar receita",state.query||state.category!=="Todas"?"recipes":"form")}`;
  $("#recipe-search")?.addEventListener("input", e=>{state.query=e.target.value; renderRecipes(); const i=$("#recipe-search"); i?.focus(); i?.setSelectionRange(state.query.length,state.query.length);});
  $("#sort-select")?.addEventListener("change", e=>{state.sort=e.target.value; renderRecipes();});
}

function ingredientRow(item={}) { return `<div class="ingredient-row"><input class="ing-qty" value="${escapeHtml(item.qty||"")}" placeholder="Qtd."><input class="ing-unit" value="${escapeHtml(item.unit||"")}" placeholder="Unid."><input class="ing-name" value="${escapeHtml(item.name||"")}" placeholder="Ingrediente"><button type="button" class="remove-ingredient" aria-label="Remover ingrediente">${icon("trash")}</button></div>`; }

function renderForm(id=null) {
  state.editingId=id; state.imageFile=null;
  const recipe=id?state.recipes.find(r=>r.id===id):null; state.currentRecipe=recipe; state.imageUrl=recipe?.imageUrl||""; state.imagePath=recipe?.imagePath||"";
  const ingredients=recipe?.ingredients||[{qty:"",unit:"",name:""}];
  $("#view-form").innerHTML=`<div class="page-heading form-heading"><div><button class="back-button" data-view="${id?"detail":"recipes"}" ${id?`data-id="${id}"`:""}>${icon("back")} Voltar</button><span class="eyebrow">${id?"EDITAR RECEITA":"NOVA RECEITA"}</span><h1>${id?"Aperfeiçoe sua receita.":"Vamos guardar esse sabor."}</h1><p>Preencha os detalhes no seu ritmo.</p></div></div>
  <form id="recipe-form" class="recipe-form"><div class="form-card"><div class="form-card-title"><span class="step-number">01</span><div><h2>Identidade</h2><p>Como essa receita se chama?</p></div></div><div class="photo-picker"><div id="photo-preview" class="photo-preview">${state.imageUrl?`<img src="${escapeHtml(state.imageUrl)}" alt="Prévia da receita">`:`<div>${icon("image")}<strong>Foto da receita</strong><small>Toque para escolher</small></div>`}</div><input id="recipe-image-gallery" type="file" accept="image/*" hidden><input id="recipe-image-camera" type="file" accept="image/*" capture="environment" hidden><div><div class="photo-actions"><label class="upload-button" for="recipe-image-gallery">${icon("image")} ${state.imageUrl?"Trocar foto":"Escolher da galeria"}</label><label class="upload-button" for="recipe-image-camera">${icon("image")} Câmera</label></div><p class="field-help">Escolha uma foto da galeria ou tire uma nova. A foto é otimizada antes do upload.</p></div></div>
  <label>Nome da receita *<input id="recipe-title" required maxlength="120" value="${escapeHtml(recipe?.title||"")}" placeholder="Ex.: Bolo de chocolate da família"></label><div class="form-grid"><label>Categoria<select id="recipe-category"><option value="">Selecione</option>${categories.map(c=>`<option ${recipe?.category===c?"selected":""}>${c}</option>`).join("")}</select></label><label>Tempo de preparo<input id="recipe-time" value="${escapeHtml(recipe?.prepTime||"")}" placeholder="Ex.: 45 min"></label><label>Rendimento<input id="recipe-servings" value="${escapeHtml(recipe?.servings||"")}" placeholder="Ex.: 10 porções"></label></div><label>Descrição<textarea id="recipe-description" rows="3" maxlength="500" placeholder="Uma pequena história ou descrição…">${escapeHtml(recipe?.description||"")}</textarea></div>
  <div class="form-card"><div class="form-card-title"><span class="step-number">02</span><div><h2>Ingredientes</h2><p>Liste tudo que entra no preparo.</p></div></div><div id="ingredients-list">${ingredients.map(ingredientRow).join("")}</div><button type="button" id="add-ingredient" class="outline-button">${icon("plus")} Adicionar ingrediente</button></div>
  <div class="form-card"><div class="form-card-title"><span class="step-number">03</span><div><h2>Preparo</h2><p>Use uma linha para cada etapa — isso habilita o modo cozinhar.</p></div></div><label>Modo de preparo<textarea id="recipe-preparation" rows="10" placeholder="Ex.: Misture os ingredientes secos.\nAdicione os líquidos.\nLeve ao forno…">${escapeHtml(recipe?.preparation||"")}</textarea></label></div>
  <div class="form-card"><div class="form-card-title"><span class="step-number">04</span><div><h2>Seu toque</h2><p>Custos, segredos e observações pessoais.</p></div></div><div class="form-grid cost-grid"><label>Custo total (opcional)<input id="recipe-cost" inputmode="decimal" value="${escapeHtml(recipe?.costTotal||"")}" placeholder="Ex.: 25,50"></label><label>Custo por porção<input id="recipe-cost-per" readonly value="${escapeHtml(recipe?.costPerServing||"")}" placeholder="Calculado automaticamente"></label><div class="cost-tip">Informe o custo total e o rendimento em número de porções para calcular.</div></div><label>Observações<textarea id="recipe-notes" rows="5" placeholder="Segredos, substituições, dicas, ajustes…">${escapeHtml(recipe?.notes||"")}</textarea></div>
  <div class="form-actions"><button type="button" class="outline-button" data-view="${id?"detail":"recipes"}" ${id?`data-id="${id}"`:""}>Cancelar</button><button id="save-recipe" class="btn btn-primary" type="submit">${icon("check")} ${id?"Salvar alterações":"Salvar receita"}</button></div></form>`;
  bindFormEvents(); calculateCost();
}

function bindFormEvents(){
  const form=$("#recipe-form"); $("#add-ingredient")?.addEventListener("click",()=>$("#ingredients-list").insertAdjacentHTML("beforeend",ingredientRow()));
  $("#ingredients-list")?.addEventListener("click",e=>{if(e.target.closest(".remove-ingredient")){const rows=$$(".ingredient-row");if(rows.length>1)e.target.closest(".ingredient-row").remove();else toast("Mantenha pelo menos uma linha de ingrediente.","error");}});
  const handleImageSelection = e => {
    const file = e.target.files?.[0];
    if (!file) return;
    const looksLikeImage = (file.type && file.type.startsWith("image/")) || /\.(jpe?g|png|webp|gif|bmp|heic|heif|avif)$/i.test(file.name || "");
    if (!looksLikeImage) { toast("Escolha uma foto válida (JPG, PNG ou WEBP).", "error"); e.target.value = ""; return; }
    if (file.size > 15 * 1024 * 1024) { toast("A foto deve ter no máximo 15 MB.", "error"); e.target.value = ""; return; }
    state.imageFile = file;
    const url = URL.createObjectURL(file);
    const preview = $("#photo-preview");
    if (preview) {
      preview.innerHTML = `<img src="${url}" alt="Prévia da receita">`;
      preview.querySelector("img")?.addEventListener("error", () => {
        preview.innerHTML = `<div>${icon("image")}<strong>Foto selecionada</strong><small>Será convertida antes do envio.</small></div>`;
      }, { once: true });
    }
    // Permite escolher novamente a mesma foto depois de removê-la/trocá-la.
    e.target.value = "";
  };
  $("#recipe-image-gallery")?.addEventListener("change",handleImageSelection);
  $("#recipe-image-camera")?.addEventListener("change",handleImageSelection);
  $("#recipe-cost")?.addEventListener("input",calculateCost); $("#recipe-servings")?.addEventListener("input",calculateCost);
  form?.addEventListener("submit",async e=>{e.preventDefault();const title=$("#recipe-title").value.trim();if(!title)return toast("Digite o nome da receita.","error");const ingredients=$$(".ingredient-row").map(row=>({qty:row.querySelector(".ing-qty")?.value.trim()||"",unit:row.querySelector(".ing-unit")?.value.trim()||"",name:row.querySelector(".ing-name")?.value.trim()||""})).filter(i=>i.name||i.qty||i.unit);const data={title,category:$("#recipe-category").value,description:$("#recipe-description").value.trim(),ingredients,preparation:$("#recipe-preparation").value.trim(),prepTime:$("#recipe-time").value.trim(),servings:$("#recipe-servings").value.trim(),notes:$("#recipe-notes").value.trim(),costTotal:$("#recipe-cost").value.trim(),costPerServing:$("#recipe-cost-per").value.trim(),favorite:state.currentRecipe?.favorite||false};const button=$("#save-recipe");setBusy(button,true,"Salvando…");try{const id=await saveRecipe({uid:state.user.uid,id:state.editingId,data,imageFile:state.imageFile,existingImagePath:state.imagePath});state.recipes=await loadUserRecipes(state.user.uid);toast(state.editingId?"Receita atualizada com sucesso!":"Receita salva no seu caderno!");navigate("detail",{id});}catch(error){console.error(error);toast(friendlyError(error),"error");}finally{setBusy(button,false);}});
}
function parseNumber(text=""){const m=String(text).replace(",",".").match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):NaN;}
function calculateCost(){const cost=$("#recipe-cost"),serv=$("#recipe-servings"),out=$("#recipe-cost-per");if(!cost||!serv||!out)return;const c=parseNumber(cost.value),s=parseNumber(serv.value);out.value=Number.isFinite(c)&&Number.isFinite(s)&&s>0?`R$ ${(c/s).toFixed(2).replace(".",",")}`:"";}

function renderDetail(id){
  const recipe=state.recipes.find(r=>r.id===id)||state.currentRecipe;if(!recipe)return navigate("recipes");state.currentRecipe=recipe;
  const image=recipe.imageUrl?`<img src="${escapeHtml(recipe.imageUrl)}" alt="${escapeHtml(recipe.title)}">`:`<div class="detail-placeholder"><span>🍲</span><small>Uma receita feita para ser lembrada.</small></div>`;
  const ingredients=(recipe.ingredients||[]).filter(i=>i.name||i.qty||i.unit);const steps=(recipe.preparation||"").split(/\n+/).map(s=>s.trim()).filter(Boolean);const cost=recipe.costPerServing?`<span>${icon("coin")} ${escapeHtml(recipe.costPerServing)}/porção</span>`:"";
  $("#view-detail").innerHTML=`<div class="detail-wrap"><div class="detail-top"><button class="back-button" data-view="recipes">${icon("back")} Minhas receitas</button><div class="detail-actions"><button class="icon-button ${recipe.favorite?"is-favorite":""}" data-favorite="${recipe.id}" aria-label="Favoritar">${icon("heart")}</button><button class="icon-button" data-edit="${recipe.id}" aria-label="Editar">${icon("edit")}</button><button class="icon-button danger" data-delete="${recipe.id}" aria-label="Excluir">${icon("trash")}</button></div></div><article class="detail-card"><div class="detail-cover">${image}</div><div class="detail-body"><div class="detail-title-row"><div><span class="tag">${escapeHtml(recipe.category||"Receita caseira")}</span><h1>${escapeHtml(recipe.title)}</h1></div><button class="cook-now" data-cook="${recipe.id}">${icon("chef")} Cozinhar agora</button></div>${recipe.description?`<p class="detail-description">${escapeHtml(recipe.description)}</p>`:""}<div class="detail-meta"><span>${icon("clock")} ${escapeHtml(recipe.prepTime||"Tempo livre")}</span><span>${icon("users")} ${escapeHtml(recipe.servings||"Porções a gosto")}</span>${cost}</div><div class="detail-tools"><button class="tool-button" data-shopping-recipe="${recipe.id}">${icon("cart")} Lista de compras</button><button class="tool-button" data-scale="${recipe.id}">${icon("scale")} Ajustar porções</button>${recipe.preparation?`<button class="tool-button" data-timer="${recipe.id}">${icon("timer")} Cronômetro</button>`:""}</div><div class="detail-sections"><section><h2>Ingredientes <small>${ingredients.length}</small></h2>${ingredients.length?`<ul class="ingredient-list">${ingredients.map(i=>`<li><span class="check-dot">${icon("check")}</span><span><strong>${escapeHtml(i.qty||"")}${i.qty&&i.unit?" ":""}${escapeHtml(i.unit||"")}</strong>${i.qty||i.unit?" ":""}${escapeHtml(i.name||"")}</span></li>`).join("")}</ul>`:`<p class="muted">Nenhum ingrediente cadastrado.</p>`}</section>${recipe.preparation?`<section><h2>Modo de preparo</h2><div class="preparation-text">${steps.map((s,i)=>`<div class="prep-step"><span>${String(i+1).padStart(2,"0")}</span><p>${escapeHtml(s)}</p></div>`).join("")}</div></section>`:""}${recipe.notes?`<section class="notes-box"><h2>Observações</h2><p>${escapeHtml(recipe.notes).replace(/\n/g,"<br>")}</p></section>`:""}</div><div class="detail-footer">Atualizada em ${formatDate(recipe.updatedAt||recipe.createdAt)||"data recente"}</div></div></article></div>`;
}

function renderSettings(){const name=state.profile?.displayName||state.user?.displayName||"";$("#view-settings").innerHTML=`<div class="page-heading"><div><span class="eyebrow">CONTA</span><h1>Perfil e ajustes</h1><p>Cuide dos seus dados e da sua experiência.</p></div></div><div class="settings-grid"><div class="settings-card profile-card"><div class="profile-big">${escapeHtml(initials(name||state.user?.email||"?"))}</div><span class="eyebrow">SEU PERFIL</span><h2>${escapeHtml(name||"Seu nome")}</h2><p>${escapeHtml(state.user?.email||"")}</p><form id="profile-form"><label>Nome de exibição<input id="profile-name" required maxlength="80" value="${escapeHtml(name)}"></label><button class="btn btn-primary" type="submit">Salvar perfil</button></form></div><div class="settings-card"><span class="eyebrow">FERRAMENTAS</span><h2>Minha Cozinha</h2><p>Receitas sincronizadas com seu Firebase.</p><div class="setting-line"><span>Receitas salvas</span><strong>${state.recipes.length}</strong></div><div class="setting-line"><span>Favoritas</span><strong>${state.recipes.filter(r=>r.favorite).length}</strong></div><div class="setting-line"><span>Itens na lista</span><strong>${state.shoppingList.filter(i=>!i.checked).length}</strong></div><button id="open-shopping-settings" class="outline-button">${icon("cart")} Abrir lista de compras</button><button id="settings-logout" class="outline-button danger-outline">${icon("logout")} Sair da conta</button></div></div>`;
  $("#profile-form")?.addEventListener("submit",async e=>{e.preventDefault();const nameValue=$("#profile-name").value.trim();if(!nameValue)return;try{await updateProfile(state.user.uid,{displayName:nameValue});state.profile.displayName=nameValue;await state.user.reload();renderSettings();renderDashboard();toast("Perfil atualizado.");}catch(error){toast(friendlyError(error),"error");}});
}

function openAuth(mode){$("#auth-login").classList.toggle("hidden",mode!=="login");$("#auth-register").classList.toggle("hidden",mode!=="register");}
function closeMobileMenu(){document.body.classList.remove("menu-open");}

async function toggleFavorite(id){const recipe=state.recipes.find(r=>r.id===id);if(!recipe)return;try{recipe.favorite=!recipe.favorite;await setRecipeFavorite(state.user.uid,id,recipe.favorite);toast(recipe.favorite?"Adicionada às favoritas.":"Removida das favoritas.");if($("#view-recipes").classList.contains("active"))renderRecipes();if($("#view-dashboard").classList.contains("active"))renderDashboard();if($("#view-detail").classList.contains("active"))renderDetail(id);}catch(error){recipe.favorite=!recipe.favorite;toast(friendlyError(error),"error");}}

async function loadShopping(){try{state.shoppingList=await getShoppingList(state.user.uid);}catch(error){console.error(error);state.shoppingList=[];}}
async function addRecipeToShopping(recipe){const existing=state.shoppingList;for(const item of (recipe.ingredients||[])){if(!item.name)continue;const found=existing.find(x=>x.name.toLowerCase()===item.name.toLowerCase()&&!x.checked);if(found){found.qty=[found.qty,item.qty].filter(Boolean).join(" + ");found.unit=found.unit||item.unit;}else existing.push({id:`item-${Date.now()}-${Math.random().toString(16).slice(2)}`,name:item.name,qty:item.qty||"",unit:item.unit||"",checked:false,createdAt:Date.now()});}await saveShoppingList(state.user.uid,existing);await loadShopping();toast("Ingredientes adicionados à lista de compras.");openShoppingModal();}
function openShoppingModal(){let modal=$("#shopping-modal");if(!modal){modal=document.createElement("div");modal.id="shopping-modal";modal.className="modal-backdrop";document.body.appendChild(modal);}renderShoppingModal();modal.classList.add("open");}
function renderShoppingModal(){const modal=$("#shopping-modal");if(!modal)return;const unchecked=state.shoppingList.filter(i=>!i.checked),checked=state.shoppingList.filter(i=>i.checked);modal.innerHTML=`<div class="modal-card shopping-modal"><div class="modal-head"><div><span class="eyebrow">COZINHA PRÁTICA</span><h2>Lista de compras</h2></div><button class="icon-button" data-close-modal>${icon("close")}</button></div><div class="shopping-add"><input id="shopping-new" placeholder="Adicionar item manualmente…"><button class="btn btn-primary" id="shopping-add-btn">${icon("plus")} Adicionar</button></div><div class="shopping-list">${unchecked.length?unchecked.map(shoppingItem).join(""):"<p class=\"muted empty-shopping\">Sua lista está limpa. Adicione ingredientes de uma receita.</p>"}${checked.length?`<div class="checked-title">Concluídos</div>${checked.map(shoppingItem).join("")}`:""}</div><div class="modal-foot"><button class="outline-button" id="clear-shopping">Limpar concluídos</button><button class="btn btn-light" data-close-modal>Fechar</button></div></div>`;modal.querySelector("#shopping-add-btn")?.addEventListener("click",async()=>{const input=modal.querySelector("#shopping-new"),name=input.value.trim();if(!name)return;state.shoppingList.push({id:`item-${Date.now()}`,name,qty:"",unit:"",checked:false,createdAt:Date.now()});await saveShoppingList(state.user.uid,state.shoppingList);input.value="";renderShoppingModal();});modal.querySelector("#clear-shopping")?.addEventListener("click",async()=>{state.shoppingList=state.shoppingList.filter(i=>!i.checked);await saveShoppingList(state.user.uid,state.shoppingList);renderShoppingModal();});}
function shoppingItem(item){return `<label class="shopping-item"><input type="checkbox" data-shopping-check="${escapeHtml(item.id)}" ${item.checked?"checked":""}><span>${escapeHtml([item.qty,item.unit].filter(Boolean).join(" "))}</span><strong>${escapeHtml(item.name)}</strong></label>`;}

function openScaleModal(recipe){let modal=$("#scale-modal");if(!modal){modal=document.createElement("div");modal.id="scale-modal";modal.className="modal-backdrop";document.body.appendChild(modal);}const original=parseNumber(recipe.servings)||1;modal.innerHTML=`<div class="modal-card"><div class="modal-head"><div><span class="eyebrow">AJUSTE INTELIGENTE</span><h2>Ajustar porções</h2></div><button class="icon-button" data-close-modal>${icon("close")}</button></div><p class="muted">Original: ${escapeHtml(recipe.servings||"1 porção")}</p><label>Quero fazer<input id="scale-number" type="number" min="1" step="1" value="${original}"></label><div id="scale-result" class="scale-result"></div><div class="modal-foot"><button class="btn btn-light" data-close-modal>Fechar</button></div></div>`;modal.classList.add("open");const input=$("#scale-number"),result=$("#scale-result");const update=()=>{const target=Math.max(1,Number(input.value)||1),factor=target/original;result.innerHTML=`<h3>Ingredientes para ${target} porções</h3>${(recipe.ingredients||[]).filter(i=>i.name).map(i=>{const n=parseNumber(i.qty);const qty=Number.isFinite(n)?formatScaled(n*factor):i.qty;return `<div><strong>${escapeHtml(qty)} ${escapeHtml(i.unit||"")}</strong> ${escapeHtml(i.name)}</div>`;}).join("")}`;};input.addEventListener("input",update);update();}
function formatScaled(n){return Number.isInteger(n)?String(n):String(Math.round(n*100)/100).replace(".",",");}

function openTimer(recipe){let modal=$("#timer-modal");if(!modal){modal=document.createElement("div");modal.id="timer-modal";modal.className="modal-backdrop";document.body.appendChild(modal);}const base=parseNumber(recipe.prepTime)||10;state.timerSeconds=base*60;state.timerTotal=state.timerSeconds;clearInterval(state.timer);modal.innerHTML=`<div class="modal-card timer-modal"><div class="modal-head"><div><span class="eyebrow">MODO COZINHA</span><h2>Cronômetro</h2></div><button class="icon-button" data-close-modal>${icon("close")}</button></div><div id="timer-display" class="timer-display">${formatTimer(state.timerSeconds)}</div><div class="timer-presets"><button data-min="5">5 min</button><button data-min="10">10 min</button><button data-min="20">20 min</button><button data-min="30">30 min</button></div><div class="timer-actions"><button class="btn btn-primary" id="timer-start">▶ Iniciar</button><button class="outline-button" id="timer-reset">↺ Reiniciar</button></div></div>`;modal.classList.add("open");modal.querySelectorAll("[data-min]").forEach(b=>b.addEventListener("click",()=>{state.timerSeconds=Number(b.dataset.min)*60;state.timerTotal=state.timerSeconds;updateTimerDisplay();}));modal.querySelector("#timer-start").addEventListener("click",()=>{if(state.timer)clearInterval(state.timer);state.timer=setInterval(()=>{state.timerSeconds--;updateTimerDisplay();if(state.timerSeconds<=0){clearInterval(state.timer);state.timer=null;toast("Tempo concluído! Hora de conferir a receita. ");}},1000);});modal.querySelector("#timer-reset").addEventListener("click",()=>{clearInterval(state.timer);state.timer=null;state.timerSeconds=state.timerTotal;updateTimerDisplay();});}
function formatTimer(s){return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;}
function updateTimerDisplay(){const el=$("#timer-display");if(el)el.textContent=formatTimer(state.timerSeconds);}
function openCookMode(recipe){const steps=(recipe.preparation||"").split(/\n+/).map(s=>s.trim()).filter(Boolean);if(!steps.length)return toast("Adicione uma etapa por linha no modo de preparo.","error");let modal=$("#cook-modal");if(!modal){modal=document.createElement("div");modal.id="cook-modal";modal.className="modal-backdrop cook-backdrop";document.body.appendChild(modal);}let index=0;const draw=()=>{modal.innerHTML=`<div class="cook-card"><div class="cook-head"><span>${escapeHtml(recipe.title)}</span><button class="icon-button" data-close-modal>${icon("close")}</button></div><div class="cook-progress">ETAPA ${index+1} DE ${steps.length}</div><div class="cook-step-number">${String(index+1).padStart(2,"0")}</div><p class="cook-step-text">${escapeHtml(steps[index])}</p><div class="cook-actions"><button class="outline-button" id="cook-prev" ${index===0?"disabled":""}>← Anterior</button><button class="btn btn-primary" id="cook-next">${index===steps.length-1?"Concluir ✓":"Próxima →"}</button></div></div>`;modal.querySelector("#cook-prev")?.addEventListener("click",()=>{index--;draw();});modal.querySelector("#cook-next")?.addEventListener("click",()=>{if(index<steps.length-1){index++;draw();}else{modal.classList.remove("open");toast("Preparo concluído! Bom apetite.");}});modal.classList.add("open");};draw();}

async function initUser(user,profile,meta={}){state.user=user;state.profile=profile||{};if(!user){showScreen("auth");return;}showScreen("app");$("#mobile-avatar").textContent=initials(profile?.displayName||user.displayName||user.email);if(meta.databaseReady===false&&meta.error)toast(friendlyError(meta.error),"error");try{state.recipes=await loadUserRecipes(user.uid);await loadShopping();renderDashboard();}catch(error){console.error(error);toast("Não foi possível carregar suas receitas.","error");renderDashboard();}}

function bindGlobalEvents(){document.addEventListener("click",async e=>{
  const close=e.target.closest("[data-close-modal]");if(close){close.closest(".modal-backdrop")?.classList.remove("open");return;}
  const viewButton=e.target.closest("[data-view]");if(viewButton){navigate(viewButton.dataset.view,{id:viewButton.dataset.id});return;}
  const authSwitch=e.target.closest("[data-auth-switch]");if(authSwitch){openAuth(authSwitch.dataset.authSwitch);return;}
  const category=e.target.closest("[data-category]");if(category){state.category=category.dataset.category;renderRecipes();return;}
  const card=e.target.closest(".recipe-card");if(card&&!e.target.closest("button")){navigate("detail",{id:card.dataset.recipeId});return;}
  const fav=e.target.closest("[data-favorite]");if(fav){e.stopPropagation();await toggleFavorite(fav.dataset.favorite);return;}
  const edit=e.target.closest("[data-edit]");if(edit){navigate("form",{id:edit.dataset.edit});return;}
  const del=e.target.closest("[data-delete]");if(del){const recipe=state.recipes.find(r=>r.id===del.dataset.delete);if(!recipe)return;if(!confirm(`Excluir “${recipe.title}”? Essa ação não pode ser desfeita.`))return;try{await removeRecipe({uid:state.user.uid,recipe});state.recipes=await loadUserRecipes(state.user.uid);toast("Receita excluída.");navigate("recipes");}catch(error){toast(friendlyError(error),"error");}return;}
  const shopRecipe=e.target.closest("[data-shopping-recipe]");if(shopRecipe){const recipe=state.recipes.find(r=>r.id===shopRecipe.dataset.shoppingRecipe);if(recipe)await addRecipeToShopping(recipe);return;}
  const scale=e.target.closest("[data-scale]");if(scale){const recipe=state.recipes.find(r=>r.id===scale.dataset.scale);if(recipe)openScaleModal(recipe);return;}
  const timer=e.target.closest("[data-timer]");if(timer){const recipe=state.recipes.find(r=>r.id===timer.dataset.timer);if(recipe)openTimer(recipe);return;}
  const cook=e.target.closest("[data-cook]");if(cook){const recipe=state.recipes.find(r=>r.id===cook.dataset.cook);if(recipe)openCookMode(recipe);return;}
  if(e.target.closest("#open-shopping")||e.target.closest("#open-shopping-settings")){openShoppingModal();return;}
  const check=e.target.closest("[data-shopping-check]");if(check){const item=state.shoppingList.find(i=>i.id===check.dataset.shoppingCheck);if(item){item.checked=check.checked;await saveShoppingList(state.user.uid,state.shoppingList);if($("#shopping-modal")?.classList.contains("open"))renderShoppingModal();}} 
  if(e.target.closest("#logout-button")||e.target.closest("#settings-logout")){await logoutUser();return;}
});
$("#mobile-menu")?.addEventListener("click",()=>document.body.classList.toggle("menu-open"));
$("#login-form")?.addEventListener("submit",async e=>{e.preventDefault();const button=e.target.querySelector("button[type=submit]");setBusy(button,true,"Entrando…");try{await loginUser($("#login-email").value.trim(),$("#login-password").value);}catch(error){toast(friendlyError(error),"error");}finally{setBusy(button,false);}});
$("#register-form")?.addEventListener("submit",async e=>{e.preventDefault();const name=$("#register-name").value.trim(),email=$("#register-email").value.trim(),password=$("#register-password").value,confirmPassword=$("#register-confirm").value;if(password!==confirmPassword)return toast("As senhas não coincidem.","error");const button=e.target.querySelector("button[type=submit]");setBusy(button,true,"Criando…");try{await registerUser({displayName:name,email,password});toast("Conta criada! Bem-vindo ao seu caderno.");}catch(error){toast(friendlyError(error),"error");}finally{setBusy(button,false);}});
$("#forgot-password")?.addEventListener("click",async()=>{const email=$("#login-email").value.trim();if(!email)return toast("Digite seu e-mail primeiro.","error");try{await resetPassword(email);toast("Enviamos um link para redefinir sua senha.");}catch(error){toast(friendlyError(error),"error");}});
}
bindGlobalEvents();
if(!isConfigured){showScreen("auth");toast("Firebase ainda não foi configurado. Veja o README.","error");}else{watchAuth(initUser);}
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("/service-worker.js").catch(console.error));
